version: 2.1

workflows:
  build:
    jobs:
      - build-lib
      - build-jar:
          requires:
            - build-lib

jobs:
  build-lib:
    docker:
      - image: 'cppbuild/alpine-gxx'

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: |
             cd build
             cmake ../srcs
             cmake --build .
      
      - store_artifacts:
          path: build/lib
      
      - persist_to_workspace:
          root: .
          paths:
            - build
            - srcs
            
  build-jar:
    docker:
      - image: 'circleci/openjdk:13-jdk-buster'
    
    steps:
      - attach_workspace:
          at: ./ws

      - run: |
             cd ws/build/java-desktop
             gradle build

      - store_artifacts:
          path: ws/build/java-desktop/build/libs
      - store_artifacts:
          path: ws/build//lib/libheifjni.so

