version: 2.1

executors:
  docker-builder:
    docker:
      - image: 'docker.io/jorjazo/debian-build-env:latest'

workflows:
  build:
    jobs:
      - build-lib
      - build-jar:
          requires:
            - build-lib

jobs:
  build-lib:
    executor: docker-builder

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: |
             ls $CIRCLE_WORKING_DIRECTORY
             cd $CIRCLE_WORKING_DIRECTORY/build
             cmake ../srcs
             cmake --build .
      
      - store_artifacts:
          path: build/lib
      
      - persist_to_workspace:
          root: .
          paths:
            - build
            - srcs
            
  build-jar:
    executor: docker-builder
    
    steps:
      - attach_workspace:
          at: ./ws

      - run: |
             cd $CIRCLE_WORKING_DIRECTORY/build/java-desktop
             gradle build

      - store_artifacts:
          path: build/lib/java-desktop
